version: '3.8'
services:
  flux:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLUX_DATABASE_URL=postgresql://user:pass@db:5432/flux
      - FLUX_CACHE_REDIS_HOST=redis
      - FLUX_EXECUTOR_DISTRIBUTED_CONFIG_RABBITMQ_HOST=rabbitmq
    volumes:
      - ./flux.toml:/app/flux.toml
    depends_on:
      - db
      - redis
      - rabbitmq
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=flux
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
