# MkDocs configuration for Flux documentation
site_name: Flux Documentation
site_description: Distributed workflow orchestration engine to build stateful and fault-tolerant workflows
site_author: Flux Contributors
repo_url: https://github.com/edurdias/flux
repo_name: edurdias/flux

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
  language: en
  palette:
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/edurdias/flux
      name: Flux on GitHub
  analytics:
    provider: google
    property: UA-XXXXX-Y  # Replace with your Google Analytics ID
  generator: false  # Hide "Made with MkDocs" for cleaner branding

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [flux]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            filters: ["!^_"]
            members: ["workflow", "task", "WorkflowExecutionContext", "CacheManager", "DistributedExecutor"]
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - social:
      cards_layout: default

nav:
  - Home: index.md
  - Introduction:
      - Overview: introduction/overview.md
      - Key Features: introduction/features.md
      - Use Cases: introduction/use-cases.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Basic Concepts: getting-started/basic_concepts.md
      - Quick Start: getting-started/quick-start-guide.md
  - Core Concepts:
      - Workflow Management: core-concepts/workflow-management.md
      - Tasks: core-concepts/tasks.md
      - Error Handling: core-concepts/error-handling.md
      - Execution Model: core-concepts/execution-model.md
  - Advanced Features:
      - Task Patterns: advanced-features/task-patterns.md
      - Workflow Controls: advanced-features/workflow-controls.md
      - Output Storage: advanced-features/output-storage.md
      - Secrets Management: advanced-features/secrets-management.md
      - Caching: advanced-features/caching.md
      - Distributed Execution: advanced-features/distributed-execution.md
  - Deployment:
      - Docker: deployment/docker.md
      - Kubernetes: deployment/kubernetes.md
      - Serverless: deployment/serverless.md
  - Configuration:
      - flux.toml: configuration/flux-toml.md
      - Environment Variables: configuration/environment-variables.md
  - Examples:
      - Basic Workflows: examples/basic.md
      - Complex Workflows: examples/complex.md
      - Error Handling: examples/error-handling.md
      - Parallel Processing: examples/parallel.md
      - Serverless Workflows: examples/serverless.md
  - API Reference:
      - Workflow: api/workflow.md
      - Task: api/task.md
      - Context: api/context.md
      - Events: api/events.md
      - CacheManager: api/cache-manager.md
      - Executors: api/executors.md
  - Licensing:
      - Apache 2.0 License: licensing/license.md
      - Third-Party Notices: licensing/notice.md
  - Contributing: contributing.md
